export const Nunito = {
  Black: require("../assets/fonts/Nunito-Black.ttf"),
  BlackItalic: require("../assets/fonts/Nunito-BlackItalic.ttf"),
  Bold: require("../assets/fonts/Nunito-Bold.ttf"),
  BoldItalic: require("../assets/fonts/Nunito-BoldItalic.ttf"),
  ExtraBold: require("../assets/fonts/Nunito-ExtraBold.ttf"),
  ExtraBoldItalic: require("../assets/fonts/Nunito-ExtraBoldItalic.ttf"),
  ExtraLight: require("../assets/fonts/Nunito-ExtraLight.ttf"),
  ExtraLightItalic: require("../assets/fonts/Nunito-ExtraLightItalic.ttf"),
  Italic: require("../assets/fonts/Nunito-Italic.ttf"),
  Light: require("../assets/fonts/Nunito-Light.ttf"),
  LightItalic: require("../assets/fonts/Nunito-LightItalic.ttf"),
  Medium: require("../assets/fonts/Nunito-Medium.ttf"),
  MediumItalic: require("../assets/fonts/Nunito-MediumItalic.ttf"),
  Regular: require("../assets/fonts/Nunito-Regular.ttf"),
  SemiBold: require("../assets/fonts/Nunito-SemiBold.ttf"),
  SemiBoldItalic: require("../assets/fonts/Nunito-SemiBoldItalic.ttf"),
};

export const fontFamily = {
  black: "Black",
  blackItalic: "BlackItalic",
  bold: "Bold",
  boldItalic: "BoldItalic",
  extraBold: "ExtraBold",
  extraBoldItalic: "ExtraBoldItalic",
  extraLight: "ExtraLight",
  extraLightItalic: "ExtraLightItalic",
  italic: "Italic",
  light: "Light",
  lightItalic: "LightItalic",
  medium: "Medium",
  mediumItalic: "MediumItalic",
  regular: "Regular",
  semiBold: "SemiBold",
  semiBoldItalic: "SemiBoldItalic",
};
